kinematics:
  shoulder:
    x: 0
    y: 0
    z: 0.1805565765491204
    roll: -0
    pitch: 0
    yaw: -2.170040808050042e-07
  upper_arm:
    x: -0.0001442006930162102
    y: 0
    z: 0
    roll: 1.570528554791526
    pitch: 0
    yaw: -4.017686576594957e-06
  forearm:
    x: -0.6123059880229028
    y: 0
    z: 0
    roll: 0.0006455477336211541
    pitch: 0.0003167931559577983
    yaw: 1.517166328859846e-05
  wrist_1:
    x: -0.5708341867174032
    y: 0.0010178121946284
    z: 0.1748816969251616
    roll: 3.135772715192424
    pitch: 3.139213743757745
    yaw: 3.141587677385887
  wrist_2:
    x: 0.0001032557588562822
    y: -0.1200673300838228
    z: -0.0004526891168180937
    roll: 1.574566602785134
    pitch: 0
    yaw: 5.452969567819614e-07
  wrist_3:
    x: -7.154662844808774e-05
    y: 0.1157119374225452
    z: -4.031095775000252e-05
    roll: 1.570447953437599
    pitch: 3.141592653589793
    yaw: -3.141592584612189
  hash: calib_3302601187690082446
